dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
services:
  - mysql
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
script:
- test/run.sh